Add nicer error message

diff --git a/bin/.local/bin/check_vpn b/bin/.local/bin/check_vpn
--- a/bin/.local/bin/check_vpn
+++ b/bin/.local/bin/check_vpn
@@ -2,6 +2,11 @@
 
 set -e
 
+if ! command -v ifconfig &> /dev/null; then
+    echo "Command ifconfig not found"
+    exit
+fi
+
 if ifconfig | grep tun0 > /dev/null; then
     if ifconfig | grep ppp0 > /dev/null; then
         echo "Both VPNs active"
